#!/bin/bash

ucsver="5.0"
app_ver="$APP_VER"
image_ver="$IMAGE_VER"

process_ini_files() {
  local ini_files=(*.ini)

  for ini_file in "${ini_files[@]}"; do
    sed -i 's|appversion|$app_ver|' $ini_file
    sed -i 's|imageversion|$image_ver|' $ini_file
    local dir_name="${ini_file%.ini}"
    generate_command "$dir_name" "$ini_file"
  done
}

generate_command() {
  local dir=$1
  local ini_file=$2
  local files=("$dir"/*)

  $appcenterctl new-version $credentials $ucsver/$dir_name $ucsver/$dir_name:$app_ver

  command="$appcenterctl upload $credentials --noninteractive $ucsver/$dir_name:$app_ver \"

  for file in "${files[@]}"; do
    command+="$file \"
  done

  command+="$ini_file"

  $command

}

process_ini_files
