#!/bin/bash

ucsver="5.0"
app_ver="$APP_VER"
image_ver="$IMAGE_VER"

process_ini_files() {
  local ini_files=(*.ini) 

  if [ ${#ini_files[@]} -eq 0 ]; then
    echo "No .ini files in this dir"
    exit 1
  fi

  for ini_file in "${ini_files[@]}"; do
    command4="sed -i 's|appversion|$app_ver|' $ini_file"
    command5="sed -i 's|imageversion|$image_ver|' $ini_file"
    local dir_name="${ini_file%.ini}"

    if [ -d "$dir_name" ]; then
      generate_command "$dir_name"
    else
      echo "Dir $dir_name doesn't exist, skipping..."
    fi
  done
}

generate_command() {
  local dir=$1
  local files=("$dir"/*) 
  local command="$appcenterctl upload $credentials --noninteractive $ucsver/$dir_name:$app_ver \\"

  command2="$appcenterctl new-version $credentials $ucsver/$dir_name $ucsver/$dir_name:$app_ver"

  for file in "${files[@]}"; do
    command+="$file \\"
  done

  echo -e $command2
  echo =e $command4
  echo =e $command5
  echo -e ${command::-2}
}

process_ini_files
