name: test script
run-name: Publish app version ${{ inputs.ver }}

on:
  workflow_dispatch:
    inputs:
      ver:
        description: "Apps Version"
        default: "x.x.x.x"
      docker_ver:
        description: "Image version"
        default: "x.x.x.x"
env:
  credentials: --username ${{ secrets.PORTAL_USER }} --pwdfile ./pwdfile
  app: 5.0/onlyoffice-ds
  app_ee: 5.0/onlyoffice-ds-integration
  appver: 5.0/onlyoffice-ds=${{ inputs.ver }}
  appver_ee: 5.0/onlyoffice-ds-integration=${{ inputs.ver }}
  community_ini_path: onlyoffice-ds/onlyoffice-ds.ini
  ee_ini_path: onlyoffice-ds-integration/onlyoffice-ds-integration.ini
  appcenterctl: ./univention-appcenter-control
  
jobs:
  publish_apps:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.x'
      
      - name: push_script
        run: |
         chmod +x onlyoffice-ds/push_script
         \onlyoffice-ds/push_script
 
