name: test script
run-name: Publish app version ${{ inputs.ver }}

on:
  workflow_dispatch:
    inputs:
      ver:
        description: "Apps Version"
        default: "x.x.x.x"
      docker_ver:
        description: "Image version"
        default: "x.x.x.x"
env:
  credentials: --username ${{ secrets.PORTAL_USER }} --pwdfile ./pwdfile
  app: 5.0/onlyoffice-ds
  app_ee: 5.0/onlyoffice-ds-integration
  appver: 5.0/onlyoffice-ds=${{ inputs.ver }}
  appver_ee: 5.0/onlyoffice-ds-integration=${{ inputs.ver }}
  community_ini_path: Community/onlyoffice-ds.ini
  ee_ini_path: Enterprise/onlyoffice-ds-integration.ini
  appcenterctl: ./univention-appcenter-control
  
jobs:
  publish_apps:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.x'
      
      - name: push_script
        run: |
         curl -O https://provider-portal.software-univention.de/appcenter-selfservice/univention-appcenter-control
         chmod +x univention-appcenter-control
         echo "${{ secrets.PORTAL_PWD }}" > pwdfile
         $appcenterctl new-version $credentials $app $appver
         $appcenterctl upload $credentials --noninteractive $appver \
           onlyoffice-ds/LICENSE_AGREEMENT_EN \
           onlyoffice-ds/LICENSE_AGREEMENT_DE \
         $appcenterctl new-version $credentials $app_ee $appver_ee
         $appcenterctl upload $credentials --noninteractive $appver_ee \
           onlyoffice-ds-integration/LICENSE_AGREEMENT_EN \
           onlyoffice-ds-integration/LICENSE_AGREEMENT_DE \
