name: test vars

on:
  workflow_dispatch:
    inputs:
      ver:
        description: "Version"
        default: "8.2.1.1.x"
env:
  login: --username ${{ secrets.PORTAL_USER }} --pwdfile ./pwdfile

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      
      - name: Run script
        run: |
         curl -O https://provider-portal.software-univention.de/appcenter-selfservice/univention-appcenter-control
         chmod +x univention-appcenter-control
         echo "${{ secrets.PORTAL_PWD }}" > pwdfile
         ./univention-appcenter-control list $login
