name: Metadata Get

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Version"
        default: "0.0.0.0"

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      
      - name: Run script
        run: |
         curl +O https://provider-portal.software-univention.de/appcenter-selfservice/univention-appcenter-control
         chmod +x univention-appcenter-control
         echo "${{ secrets.PORTAL_PWD }}" > pwdfile
         ./univention-appcenter-control get --username ${{ secrets.PORTAL_USER }} --pwdfile ./pwdfile --json 5.0/onlyoffice-ds=8.2.1.1
