name: Publish Apps
run-name: Publish app version ${{ inputs.ver }}

on:
  workflow_dispatch:
    inputs:
      ver:
        description: "Apps Version"
        default: "x.x.x.x"
      docker_ver:
        description: "Image version"
        default: "x.x.x.x"
env:
  credentials: --username ${{ secrets.PORTAL_USER }} --pwdfile ./pwdfile
  appcenterctl: ./univention-appcenter-control
  
jobs:
  publish_community:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.x'
      
      - name: push_script
        run: |
         curl -O https://provider-portal.software-univention.de/appcenter-selfservice/univention-appcenter-control
         chmod +x univention-appcenter-control
         echo "${{ secrets.PORTAL_PWD }}" > pwdfile
         chmod +x publish
         export APP_VER=${{ inputs.ver }}
         export IMAGE_VER=${{ inputs.docker_ver }}
         publish
           
