name: Publish apps
run-name: Publish apps version ${{ inputs.ver }}

on:
  workflow_dispatch:
    inputs:
      ver:
        description: "Apps Version"
        default: "x.x.x.x"

env:
  credentials: --username ${{ secrets.PORTAL_USER }} --pwdfile .././pwdfile  
jobs:
  publish_apps:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.x'
      
      - name: publish_script
        run: |
         export APP_VER=${{ inputs.ver }}
         chmod +x deploy.sh
         echo "${{ secrets.PORTAL_PWD }}" > pwdfile
         for app_dir in ./apps/*; do
           if [ -d "$app_dir" ]; then
             echo "Publishing $app_dir"
             cd "$app_dir"
             ../../deploy.sh
             cd -
           fi
          done
