name: Publish App
run-name: Publish app version ${{ inputs.ver }}

on:
  workflow_dispatch:
    inputs:
      ver:
        description: "App Version"
        default: "x.x.x.x"
      docker_ver:
        description: "Docker version"
        default: "x.x.x.x"
env:
  login: --username ${{ secrets.PORTAL_USER }} --pwdfile ./pwdfile
  app: 5.0/onlyoffice-ds
  appver: 5.0/onlyoffice-ds=${{ inputs.ver }}
  community_ini_path: Community/onlyoffice-ds.ini
  command: ./univention-appcenter-control
  
jobs:
  publish_community:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      
      - name: Run script
        run: |
         curl -O https://provider-portal.software-univention.de/appcenter-selfservice/univention-appcenter-control
         chmod +x univention-appcenter-control
         echo "${{ secrets.PORTAL_PWD }}" > pwdfile
         $command new-version $login $app $appver
         sed -i 's|^appversion.*|${{ inputs.ver }}|' $community_ini_path
         sed -i 's|^imageversion.*|onlyoffice/documentserver-ucs:${{ inputs.docker_ver }}|' $community_ini_path
         $command upload $login --noninteractive $appver \
           Community/LICENSE_AGREEMENT_EN \
           Community/LICENSE_AGREEMENT_DE \
           Community/README_APPLIANCE_EN \
           Community/README_APPLIANCE_DE \
           Community/README_EN \
           Community/README_DE \
           Community/appliance_umc_header_logo.svg \
           Community/appliance_portal_logo.svg \
           Community/appliance_logo.svg \
           Community/logo_detail_page.svg \
           Resources/logo.svg \
           Community/onlyoffice-ds.ini \
           Community/preinst \
           Community/setup \
           Community/inst \
           Community/test
           
