name: Script Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Version"
        default: "0.0.0.0"

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      
      - name: Run script
        run: |
         chmod +x univention-appcenter-control
         echo "${{ secrets.PORTAL_PWD }}" > pwdfile
         ./univention-appcenter-control new-version --username ${{ secrets.PORTAL_USER }} --pwdfile ./pwdfile 5.0/onlyoffice-ds 5.0/onlyoffice-ds=8.2.1.1
         ./univention-appcenter-control set --username ${{ secrets.PORTAL_USER }} --pwdfile ./pwdfile 5.0/onlyoffice-ds=8.2.1.1 \ --json '{"DockerImage": "onlyoffice/documentserver-ucs:8.2.1.1"}'
         univention-appcenter-control upload --username ${{ secrets.PORTAL_USER }} --pwdfile ./pwdfile --noninteractive 5.0/onlyoffice-ds=8.2.1.1 \ app.ini \ setup.sh \ preinst.sh \ joinscript.sh \ unjoinscript.sh \ Short_Descriprion \ Short_Descriprion_DE \ Descriprion \ Descriprion_DE
