name: Triggered by Repo1

on:
 repository_dispatch:
    types: [trigger-workflow]

jobs:
  triggered-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Perform actions
        run: |
          echo "Triggered by Repo1's workflow"
